services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: proxydeck
      POSTGRES_PASSWORD: proxydeck
      POSTGRES_DB: proxydeck
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: {}
